apiVersion: 1
datasources:
  - name: TradingBot-DB
    uid: tradingbot-pg
    type: postgres
    url: postgres:5432
    database: blofin_bot
    user: bot_user
    secureJsonData:
      password: secure_password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
